export const translateWeatherCondition = (condition) => {
  const translations = {
    Sunny: "Cerah",
    Clear: "Cerah",
    Cloudy: "Berawan",
    Overcast: "Mendung",
    Mist: "Berkabut",
    Blizzard: "Badai salju",
    Fog: "Kabut",
    "Partly cloudy": "Berawan sebagian",
    "Patchy rain possible": "Hujan lokal mungkin",
    "Patchy rain nearby": "Hujan gerimis di dekat sini",
    "Patchy snow possible": "Salju lokal mungkin",
    "Patchy sleet possible": "Hujan es lokal mungkin",
    "Patchy freezing drizzle possible": "Gerimis beku lokal mungkin",
    "Thundery outbreaks possible": "Kemungkinan hujan petir",
    "Blowing snow": "Salju berembus",
    "Freezing fog": "Kabut beku",
    "Patchy light drizzle": "Gerimis ringan lokal",
    "Light drizzle": "Gerimis ringan",
    "Freezing drizzle": "Gerimis beku",
    "Heavy freezing drizzle": "Gerimis beku lebat",
    "Patchy light rain": "Hujan ringan lokal",
    "Light rain": "Hujan ringan",
    "Moderate rain at times": "Hujan sedang kadang-kadang",
    "Moderate rain": "Hujan sedang",
    "Heavy rain at times": "Hujan lebat kadang-kadang",
    "Heavy rain": "Hujan lebat",
    "Light freezing rain": "Hujan beku ringan",
    "Moderate or heavy freezing rain": "Hujan beku sedang atau lebat",
    "Light sleet": "Hujan es ringan",
    "Moderate or heavy sleet": "Hujan es sedang atau lebat",
    "Patchy light snow": "Salju ringan lokal",
    "Light snow": "Salju ringan",
    "Patchy moderate snow": "Salju sedang lokal",
    "Moderate snow": "Salju sedang",
    "Patchy heavy snow": "Salju lebat lokal",
    "Heavy snow": "Salju lebat",
    "Ice pellets": "Butiran es",
    "Light rain shower": "Hujan ringan sebentar",
    "Moderate or heavy rain shower": "Hujan sedang atau lebat sebentar",
    "Torrential rain shower": "Hujan sangat lebat sebentar",
    "Light sleet showers": "Hujan es ringan sebentar",
    "Moderate or heavy sleet showers": "Hujan es sedang atau lebat sebentar",
    "Light snow showers": "Salju ringan sebentar",
    "Moderate or heavy snow showers": "Salju sedang atau lebat sebentar",
    "Light showers of ice pellets": "Hujan butiran es ringan",
    "Moderate or heavy showers of ice pellets":
      "Hujan butiran es sedang atau lebat",
    "Patchy light rain with thunder": "Hujan ringan lokal dengan petir",
    "Moderate or heavy rain with thunder":
      "Hujan sedang atau lebat dengan petir",
    "Patchy light snow with thunder": "Salju ringan lokal dengan petir",
    "Moderate or heavy snow with thunder":
      "Salju sedang atau lebat dengan petir",
  };
  return translations[condition] || condition;
};
